### ISSUE TITLE
Pagine Html

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/Html#1]
visualizza la pagina con un browser.
che differenza noti tra quello che
è stato scritto e quello che
viene visualizzato dal browser?

**Comment by LuigiVessella** [comment]
E' scritto tutto sullo stesso rigo e non rispetta gli spazi come su un normale editor di testo

**Comment by FabioZTessitore** [comment]
ho caricato il file tag.html

dimmi se tutto chiaro

**Comment by LuigiVessella** [comment]
Sisi..Chiaro

**Comment by FabioZTessitore** [comment]
## Nidificare i tag

I tag possono essere inclusi all'interno di altri tag
prestando attenzione a chiudere prima il tag interno e poi quello esterno.

Es. Il tag `em` serve a mettere in evidenza una porzione del testo
e puo' naturalmente essere utilizzato all'interno di un paragrafo.

``` html
<p>Il linguaggio HTML <em>non</em> sembra difficile</p>
```

**Comment by LuigiVessella** [comment]
Capito

**Comment by FabioZTessitore** [comment]
ok, dai un'occhiata al file paginacompleta.html per vedere come si fa una pagina. dammi ok quando pronto

**Comment by LuigiVessella** [comment]
Ok

**Comment by FabioZTessitore** [comment]
ho caricato revisioni_editoriali.html
dammi ok quando pronto

**Comment by LuigiVessella** [comment]
ok

**Comment by FabioZTessitore** [comment]
vai con testo.html

**Comment by LuigiVessella** [comment]
Ok

**Comment by FabioZTessitore** [comment]
Molti tag si utilizzano per dare significato al testo.

Cosi' come p indica un paragrafo, h1 .. h6 le intestazioni abbiamo anche:

``` html
<abbr>      abbreviazioni
<acronym>   acronimi
<cite>      citazioni
<code>      codice sorgente
<dfn>       termini da definire
<em>        evidenza
<strong>    evidenza forte
<kbd>       da inserire con la tastiera
<samp>      testo di esempio
<var>       variabili
<pre>       testo preformattato
<address>   dati di contatto
```

**Comment by FabioZTessitore** [comment]
Alcuni caratteri hanno un significato speciale
e non possono essere inseriti direttamente nelle pagine Web.

I simboli `<` e `>` per esempio servono a delimitare i tag.

In questi casi si utilizzano dei codici:

``` html
&lt;    (less than)     minore
&gt;    (greater than)  maggiore
&amp;   (ampersand)     &
```

Anche per le lettere accentate vale un discorso analogo:

```
&eacute;  é
&egrave;  è
&ograve;  ò
...
```

**Comment by LuigiVessella** [comment]
Ok
