### ISSUE TITLE
esercizio

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/Html#2]
ho caricato il file linguaggioC.html in cui è presente solo il testo, fallo diventare una pagina Web simile alla foto che ti invio qui

![linguaggioc_pt1](https://cloud.githubusercontent.com/assets/3002194/20100366/7f5f3b4a-a5bd-11e6-9292-4b1d6424332e.png)
![linguaggioc_pt2](https://cloud.githubusercontent.com/assets/3002194/20100369/80989b46-a5bd-11e6-9278-93d9abf9b3eb.png)

**Comment by LuigiVessella** [comment]
Ok, oggi lo faccio..
O almeno ci provo aha

**Comment by LuigiVessella** [comment]
Fatto(?)

**Comment by FabioZTessitore** [comment]
macché ... mancano un sacco di cose

inizia con il mettere tutti i tag di struttura della pagina

**Comment by LuigiVessella** [comment]
Giustissimo..
Prof una domanda che non c'entra con questo ma con Linux e un mio guaio ahah..
Sul portatile volevo cambiare distribuzione e ho formattato la partizione di mint da Windows..Ora all'avvio esce una schermata nera con scritto: no such partition, rescue mode, grub rescue..
Consigli??? ahah

**Comment by LuigiVessella** [comment]
Ho ricaricato il file...Mi sono scordato un sacco di cose prima

**Comment by FabioZTessitore** [comment]
prima di cominciare con i tag, non manca niente?

all'interno di head non si mette `ins`

**Comment by LuigiVessella** [comment]
Forse ho fatto..forse..

**Comment by FabioZTessitore** [comment]
ho caricato il file con dei suggerimenti. fai pull

**Comment by LuigiVessella** [comment]
""
Perchè non va bene? Quelli sono vari paragrafi e ho usato div..
h2 h3 servono per creare delle intestazioni, perchè non vanno bene?

**Comment by LuigiVessella** [comment]
div permette di creare delle divisioni.
      In questo esempio la divisione e' formata da tre paragrafi

**Comment by FabioZTessitore** [comment]
aggiustiamo una cosa alla volta

l'html serve a formattare testi e documenti. Se un testo è diviso in paragrafi devi usare p per ognuno di essi (ricorda che gli spazi non contano, quindi anche se vai a capo è come se continuassi sullo stesso rigo)

**Comment by LuigiVessella** [comment]
Io ho per la maggior parte delle cose seguito i file caricati da voi..Per esempio in testo.html il titolo si trova in head e io li l'ho messo....
br serve a mandare a capo ma sempre nello stesso paragrafo..
h1 h2 sono i tag usati nelle intestazioni...Per i paragrafi, li ho divisi io, quindi ora correggo...
Ins cite non serviva per includere la fonte dell'informazione?

**Comment by LuigiVessella** [comment]
div a che serve? Per creare delle divisioni tra i paragrafi o no?

**Comment by FabioZTessitore** [comment]
sei testardo!!!
ci sono un sacco di cose che non ti sono chiare e come ti dicevo in precedenza facciamo una cosa alla volta. comincia a mettere i paragrafi

**Comment by LuigiVessella** [comment]
Si scusate la mia testardaggine ahah, purtroppo sono così..Ecco ho caricato il file con i paragrafi messi correttamente (spero)

**Comment by FabioZTessitore** [comment]
ok, ora bisogna togliere dei tag. Mi riferisco a b e big.
I tag devono servire a dare significato al testo e NON a dire come deve essere visualizzato. Per questa ragione è bene non usare b, big e tutti quelli che modificano l'aspetto del testo senza dare significato (come u, i, ecc)

**Comment by LuigiVessella** [comment]
Ok capito..Li avevo presi da internet credendo di fare una cosa buona ahah...Li ho levati

**Comment by FabioZTessitore** [comment]
ok, adesso in fondo alla pagina aggiustiamo il codice e la firma.
quali tag sono più adatti per questi elementi?

**Comment by LuigiVessella** [comment]
Per la firma <p name....> ?
Per il codice non saprei..ora rileggo un attimo i file

**Comment by LuigiVessella** [comment]
Per la firma
p name = ...

**Comment by LuigiVessella** [comment]
Prof oggi mi rimetto a lavoro che tra progetti compiti e impegni vari non ci sono proprio riuscito

**Comment by LuigiVessella** [comment]
Ma non trovo i tag che mi servono per codice e firma..non ci sono

**Comment by FabioZTessitore** [comment]
Non ricordo se ti ho mandato il file o l'ho scritto nelle issue

Il martedì 15 novembre 2016, LuigiVessella notifications@github.com ha
scritto:

**Comment by LuigiVessella** [comment]
nelle issue, che ora non ci sono più e io non mi sono copiato ahah

**Comment by FabioZTessitore** [comment]
tra le issue ci sono anche quelle "closed"

**Comment by LuigiVessella** [comment]
ahhhh ecco..Fatto ho caricato il file con delle modifiche ma non sono riuscito a mettere la firma

**Comment by LuigiVessella** [comment]
Non so quale sia il più adatto per la firma

**Comment by FabioZTessitore** [comment]
attenzione al rigo 4
per la firma va bene address
riguardo al codice va bene code, però bisogna fare anche un'altra piccola modifica. Come sai quando si programma gli spazi contano (al contrario dell'HTML). C'è un tag che ti permette di rispettare gli spazi così come li digiti, Qual è?

**Comment by LuigiVessella** [comment]
Vedete ora..Sono insicuro tra questo e un altro

**Comment by FabioZTessitore** [comment]
è quello giusto. siccome rispetta gli spazi (e stampa tutto così com'è) devi togliere p e br

**Comment by LuigiVessella** [comment]
fatto

**Comment by FabioZTessitore** [comment]
ok, l'address non lo metti?

**Comment by LuigiVessella** [comment]
Giusto, dimenticavo

**Comment by LuigiVessella** [comment]
Ok fatto..Volevo mettere la firma a destra ma più di quello non va..Come mai?

**Comment by FabioZTessitore** [comment]
ho messo dei suggerimenti, fai pull

**Comment by LuigiVessella** [comment]
Ma la citazione Wikipedia... dove la devo mettere??Come sottotitolo oppure alla fine?

**Comment by LuigiVessella** [comment]
Sia sotto che sopra? Sopra come sottotitolo e sotto come citazione?

**Comment by FabioZTessitore** [comment]
Guarda che hai le foto come riferimento. Sveglia

Il martedì 15 novembre 2016, LuigiVessella notifications@github.com ha
scritto:

**Comment by LuigiVessella** [comment]
é la stanchezza ahah...Ok forse ho fatto..Ma come faccio a mettere il titolo più grande del sottotitolo?

**Comment by FabioZTessitore** [comment]
già ti ho scritto che non devi pensare al risultato estetico. Poi si vedrà con i CSS.

Nel codice ho scritto chiaramente che la forma del documento non è il tuo nome ... e invece di cancellare ci hai messo address ... ma come devo fare con te?

**Comment by LuigiVessella** [comment]
Prof allora potete mandarmi il prossimo esercizio..
