### ISSUE TITLE
id e class

### ISSUE THREAD

**Issue by FabioZTessitore** [LuigiVessella/Html#3]
guarda il file posts.html

**Comment by LuigiVessella** [comment]
Ok guardato

**Comment by FabioZTessitore** [comment]
crea una pagina tweets.html in cui sia presente
una lista di tweets. Scegli con attenzione gli
elementi di cui e' formato un singolo tweet.

**Comment by LuigiVessella** [comment]
Ma i tweets me li invento io?

**Comment by LuigiVessella** [comment]
Prof un problema ahah...Ho capito come dovevo fare, ho fatto, ma ho chiamato il file posts.html
e l'ho sostituito al vostro(che conteneva id e class)
Ora lo rinomino tweets.html

**Comment by FabioZTessitore** [comment]
correggi la riga 7

poi nelle classi dei vari tweet, se vuoi usare più parole, devi unirle con un `-`

**Comment by LuigiVessella** [comment]
Ok fatto
